### ISSUE TITLE
Does not work with Python 3.7

### ISSUE THREAD

**Issue by ritiek** [nsf/termbox#117]
With my `python` pointing to Python 3.7, results in a traceback:

```
$ ./waf configure
Traceback (most recent call last):
  File "/home/ritiek/Downloads/termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Node.py", line 285, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ritiek/Downloads/termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Scripting.py", line 98, in waf_entry_point
    run_commands()
  File "/home/ritiek/Downloads/termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Scripting.py", line 155, in run_commands
    parse_options()
  File "/home/ritiek/Downloads/termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Scripting.py", line 128, in parse_options
    Context.create_context('options').execute()
  File "/home/ritiek/Downloads/termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Options.py", line 138, in execute
    super(OptionsContext,self).execute()
  File "/home/ritiek/Downloads/termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Context.py", line 92, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/ritiek/Downloads/termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Context.py", line 133, in recurse
    user_function(self)
  File "/home/ritiek/Downloads/termbox/wscript", line 11, in options
    opt.load('compiler_c')
  File "/home/ritiek/Downloads/termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Context.py", line 89, in load
    fun(self)
  File "/home/ritiek/Downloads/termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Tools/compiler_c.py", line 36, in options
    opt.load_special_tools('c_*.py',ban=['c_dumbpreproc.py'])
  File "/home/ritiek/Downloads/termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Context.py", line 296, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/home/ritiek/Downloads/termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Node.py", line 334, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/home/ritiek/Downloads/termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Node.py", line 334, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration
```

Everything goes fine if `python` points to Python 2.7, 3.5 or 3.6.

**Comment by qguv** [comment]
This is because we're pulling an old version of waf which does not work for Python 3.7 ([reference](https://groups.google.com/forum/#!topic/steinwurf-dev/bZ8bltFi-a0)). The waf maintainers have [since fixed this](https://gitlab.com/ita1024/waf/commit/facdc0b173d933073832c768ec1917c553cb369c), so updating waf should close this issue.

**Comment by oblique** [comment]
Any news on this?

**Comment by rofl0r** [comment]
i guess if someone steps up and creates a PR from the above patch, the repo owner could and would click on the merge button.
