### ISSUE TITLE
npm install needs to be tweaked?

### ISSUE THREAD

**Issue by coderofsalvation** [nsf/termbox#59]
$ gcc --version
    gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2

    $ uname -a
    Linux kiwi 3.18.7-rt1 #1 SMP PREEMPT RT Mon Feb 23 07:43:39 CET 2015 x86_64 x86_64 x86_64 GNU/Linux

    $ cat /etc/issue
    Ubuntu 14.04.1 LTS \n \l

    $ npm --version
    1.4.3

    $ node --version
    v0.10.26

    $ npm install termbox
    npm http GET https://registry.npmjs.org/termbox
    npm http 200 https://registry.npmjs.org/termbox
    npm http GET https://registry.npmjs.org/termbox/-/termbox-0.1.0.tgz
    npm http 200 https://registry.npmjs.org/termbox/-/termbox-0.1.0.tgz

    > termbox@0.1.0 install /tmp/node_modules/termbox
    > node-gyp rebuild

    make: Entering directory `/tmp/node_modules/termbox/build'
      CXX(target) Release/obj.target/termbox/src/termbox.o
    ../src/termbox.cpp:13:21: fatal error: termbox.h: No such file or directory
     #include <termbox.h>
                         ^
    compilation terminated.
    make: *** [Release/obj.target/termbox/src/termbox.o] Error 1
    make: Leaving directory `/tmp/node_modules/termbox/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/mnt/data/opt/node-v0.10.26-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
    gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
    gyp ERR! System Linux 3.18.7-rt1
    gyp ERR! command "node" "/mnt/data/opt/node-v0.10.26-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /tmp/node_modules/termbox
    gyp ERR! node -v v0.10.26
    gyp ERR! node-gyp -v v0.12.2
    gyp ERR! not ok 
    npm ERR! termbox@0.1.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the termbox@0.1.0 install script.
    npm ERR! This is most likely a problem with the termbox package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls termbox
    npm ERR! There is likely additional logging output above.

    npm ERR! System Linux 3.18.7-rt1
    npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "termbox"
    npm ERR! cwd /tmp
    npm ERR! node -v v0.10.26
    npm ERR! npm -v 1.4.3
    npm ERR! code ELIFECYCLE
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /tmp/npm-debug.log
    npm ERR! not ok code 0

**Comment by nsf** [comment]
Sure, but I'm not the author of that npm package. Have no idea if he follows this github repo or not. Better contact him directly.
